#set working directory to the folder with the input files
#files needed:
#Masked_18S_ultrametric_rerooted.treefile
#the different *.csv files

require(caper)
tree<-read.tree("Masked_18S_ultrametric_rerooted.treefile")
#life history variables
dt<-read.csv("life_hist_mito_set1.csv", header=TRUE)
str(dt)
sets <- data.frame(response=character(0), predictor=character(0), AIC=numeric(0), P_value=numeric(0), adjusted_R2=numeric(0), stringsAsFactors=FALSE)

#make sure factors are interpreted as such
library(dplyr)
dt<- mutate_at(dt, vars(Habitate, Reproduction, Sex, Parasitism, Larval_stage, Diet, Venoms, Biomineralization, Extr_env, Interstitium, Deep_sea, High_Altitude, Seep, Vent, Ice), as.factor)
#make comparative data
dt_set1<-comparative.data(tree, dt, names.col="Species",warn.dropped=TRUE, na.omit=FALSE, vcv=TRUE, vcv.dim=3)
#run models
modHab<-pgls(Reverse_Dist_withRNA~Habitate, data=dt_set1, lambda = 'ML')
modRep<-pgls(Reverse_Dist_withRNA~Reproduction, data=dt_set1, lambda = 'ML')
modSex<-pgls(Reverse_Dist_withRNA~Sex, data=dt_set1, lambda = 'ML')
modParasit<-pgls(Reverse_Dist_withRNA~Parasitism, data=dt_set1, lambda = 'ML')
modLarv<-pgls(Reverse_Dist_withRNA~Larval_stage, data=dt_set1, lambda = 'ML')
modDiet<-pgls(Reverse_Dist_withRNA~Diet, data=dt_set1, lambda = 'ML')
modVenom<-pgls(Reverse_Dist_withRNA~Venoms, data=dt_set1, lambda = 'ML')
modBiomin<-pgls(Reverse_Dist_withRNA~Biomineralization, data=dt_set1, lambda = 'ML')
modExtr_env<-pgls(Reverse_Dist_withRNA~Extr_env, data=dt_set1, lambda = 'ML')
modInter<-pgls(Reverse_Dist_withRNA~Interstitium, data=dt_set1, lambda = 'ML')
modDeep<-pgls(Reverse_Dist_withRNA~Deep_sea, data=dt_set1, lambda = 'ML')
modHigh<-pgls(Reverse_Dist_withRNA~High_Altitude, data=dt_set1, lambda = 'ML')
modSeep<-pgls(Reverse_Dist_withRNA~Seep, data=dt_set1, lambda = 'ML')
modVent<-pgls(Reverse_Dist_withRNA~Vent, data=dt_set1, lambda = 'ML')
modIce<-pgls(Reverse_Dist_withRNA~Ice, data=dt_set1, lambda = 'ML')
sum_mod <- summary(modHab)
res_mod <- cbind("Reverse_Dist_withRNA", "modHab", modHab$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modRep)
res_mod <- cbind("Reverse_Dist_withRNA", "modRep", modRep$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modSex)
res_mod <- cbind("Reverse_Dist_withRNA", "modSex", modSex$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modParasit)
res_mod <- cbind("Reverse_Dist_withRNA", "modParasit", modParasit$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modLarv)
res_mod <- cbind("Reverse_Dist_withRNA", "modLarv", modLarv$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modDiet)
res_mod <- cbind("Reverse_Dist_withRNA", "modDiet", modDiet$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modVenom)
res_mod <- cbind("Reverse_Dist_withRNA", "modVeonom", modVenom$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modBiomin)
res_mod <- cbind("Reverse_Dist_withRNA", "modBiomin", modBiomin$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modExtr_env)
res_mod <- cbind("Reverse_Dist_withRNA", "modExtr_env_single", modExtr_env$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modInter)
res_mod <- cbind("Reverse_Dist_withRNA", "modInter", modInter$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modDeep)
res_mod <- cbind("Reverse_Dist_withRNA", "modDeep", modDeep$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modHigh)
res_mod <- cbind("Reverse_Dist_withRNA", "modHigh", modHigh$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modSeep)
res_mod <- cbind("Reverse_Dist_withRNA", "modSeep", modSeep$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modVent)
res_mod <- cbind("Reverse_Dist_withRNA", "modVent", modVent$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
sum_mod <- summary(modIce)
res_mod <- cbind("Reverse_Dist_withRNA", "modIce", modIce$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
dtec<-read.csv("life_hist_mito_ext_clim.csv", header=TRUE)
dtec<- mutate_at(dtec, vars(Climatic_zone), as.factor)
dtec<-comparative.data(tree, dtec, names.col="Species",warn.dropped=TRUE, na.omit=FALSE, vcv=TRUE, vcv.dim=3)
modEc<-pgls(Reverse_Dist_withRNA~Climatic_zone, data=dtec, lambda = 'ML')
sum_mod <- summary(modEc)
res_mod <- cbind("Reverse_Dist_withRNA", "modClimate", modEc$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
dte<-read.csv("life_hist_mito_ext_env.csv", header=TRUE)
dte<- mutate_at(dte, vars(Extreme_environment), as.factor)
dte<-comparative.data(tree, dte, names.col="Species",warn.dropped=TRUE, na.omit=FALSE, vcv=TRUE, vcv.dim=3)
modEE<-pgls(Reverse_Dist_withRNA~Extreme_environment, data=dte, lambda = 'ML')
sum_mod <- summary(modEE)
res_mod <- cbind("Reverse_Dist_withRNA", "modExtre_Env_multi", modEE$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
dtgt<-read.csv("life_hist_mito_ext_gen_time.csv", header=TRUE)
dtgt<- mutate_at(dtgt, vars(Gen_time), as.factor)
dtgt<-comparative.data(tree, dtgt, names.col="Species",warn.dropped=TRUE, na.omit=FALSE, vcv=TRUE, vcv.dim=3)
modGt<-pgls(Reverse_Dist_withRNA~Gen_time, data=dtgt, lambda = 'ML')
sum_mod <- summary(modGt)
res_mod <- cbind("Reverse_Dist_withRNA", "modGen_time", modGt$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
dtEg<-read.csv("life_hist_mito_ext_N_eggs.csv", header=TRUE)
dtEg<- mutate_at(dtEg, vars(eggs_offspring), as.factor)
dtEg<-comparative.data(tree, dtEg, names.col="Species",warn.dropped=TRUE, na.omit=FALSE, vcv=TRUE, vcv.dim=3)
modEg<-pgls(Reverse_Dist_withRNA~eggs_offspring, data=dtEg, lambda = 'ML')
sum_mod <- summary(modEg)
res_mod <- cbind("Reverse_Dist_withRNA", "modEgg", modEg$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
dtNr<-read.csv("life_hist_mito_ext_N_rep_seas.csv", header=TRUE)
dtNr<- mutate_at(dtNr, vars(N_rep_seas), as.factor)
dtNr<-comparative.data(tree, dtNr, names.col="Species",warn.dropped=TRUE, na.omit=FALSE, vcv=TRUE, vcv.dim=3)
modNr<-pgls(Reverse_Dist_withRNA~N_rep_seas, data=dtNr, lambda = 'ML')
sum_mod <- summary(modNr)
res_mod <- cbind("Reverse_Dist_withRNA", "modRep_seasons", modNr$aic, sum_mod$coefficients[2,4], sum_mod$adj.r.squared)
sets <- rbind(sets, res_mod)
colnames(sets) <- c("response", "predictor", "AIC", "P_Values", "adjusted_R2")
write.table(sets, "All_models_with_tRNAs.tsv", sep="\t")
